version: "3.8"

services:
  listner-block:
    build:
      context: ./block
      dockerfile: dev.Dockerfile
    volumes:
      - "./block:/home/app/"
      - /home/app/node_modules
    depends_on:
      - db
      - redis
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: "on-failure:10"
    ports:
      - 3000:3000

  listner-transactions:
    build:
      context: ./transactions
      dockerfile: dev.Dockerfile
    volumes:
      - "./transactions:/home/app/"
      - /home/app/node_modules
    depends_on:
      - db
      - redis
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: "on-failure:10"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: indexation
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
