version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: indexation
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
